topp_tracker:
  from_odom: False
  sampling_frequency: 100
  n_gridpoints: 500
  request_permission: False

  constraints:

    velocity:
      x: 5
      y: 5
      z: 5
      yaw: 2.5

    acceleration:
      x: 0.75
      y: 0.75
      z: 0.75
      yaw: 0.35
